### ISSUE TITLE
Briefing spelling

### ISSUE THREAD

**Issue by PiZZAD0X** [thecogdoctor/mpmissions#1]
https://github.com/thecogdoctor/mpmissions/blob/87e0a261223c27a3f3c1ef4720511c24174e1376/TVT54_Kirkuk_Krackdown_V3.Kidal/customization/briefing.sqf#L14

"reeking havoc" should be wreaking havoc

**Comment by PiZZAD0X** [comment]
https://github.com/thecogdoctor/mpmissions/blob/87e0a261223c27a3f3c1ef4720511c24174e1376/TVT54_Kirkuk_Krackdown_V3.Kidal/customization/briefing.sqf#L14

missing <

**Comment by thecogdoctor** [comment]
Merged into #2
